<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="STrain.CQS.Api" Version="2.0.0-rc.2" />
    <PackageReference Include="STrain.Eventing.Api" Version="3.0.0-rc.1" />
  </ItemGroup>

</Project>
