<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.3" />
    <PackageReference Include="STrain.CQS" Version="2.0.0-rc.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpecStore.Api\SpecStore.Api.csproj" />
  </ItemGroup>

</Project>
